Lookup mapped catalogs for CatalogBrains
senaite/senaite.jsonapi pull request #54
Opened 2023-03-21 15:12 UTC by ramonski

## Description of the issue/feature this PR addresses

This PR adds an additional lookup for ZCatalog brains to fetch the right catalog for metadata lookup.

## Current behavior before PR

If no `catalog` request parameter is present, the JSON API always uses `portal_catalog` to fetch the brain metadata.

## Desired behavior after PR is merged

If no `catalog` request parameter is present, the JSON API looks up the mapped catalogs for the portal type and returns the first found catalog from there for metadata lookup.

--
I confirm I have tested the PR thoroughly and coded it according to [PEP8][1]
standards.

[1]: https://www.python.org/dev/peps/pep-0008

2023-03-22 16:25 UTC, xispa requested changes
You are overwriting the `catalog` variable passed through the request

2023-03-22 16:25 UTC, xispa commented on src/senaite/jsonapi/catalog.py
> +            name = catalogs[0].getId()
`catalog` passed through the request is overwritten here. I think the lookup of the correct catalog should be done inside the `if name not in self._catalogs:` that come afterwards

2023-03-22 19:03 UTC, ramonski commented on src/senaite/jsonapi/catalog.py
> +            name = catalogs[0].getId()
Oh, I thought I did the test. Should be fixed now.

2023-03-23 04:46 UTC, xispa approved these changes

2023-03-23 04:46 UTC, merged